project/config/routes.rb
Rails.application.routes.draw do
  resources :remove_marque_form_voitures
  resources :marques
  resources :personnes
  resources :voitures
  get 'voitures/immatriculation/:imat', to: 'voitures#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project/app/models/marque.rb
class Marque < ApplicationRecord
    has_many :voitures
end

project/app/controllers/marques_controller.rb
class MarquesController < ApplicationController
  before_action :set_marque, only: [:show, :edit, :update, :destroy]

  # GET /marques
  # GET /marques.json
  def index
    @marques = Marque.all
  end

  # GET /marques/1
  # GET /marques/1.json
  def show
    @marque = Marque.find(params[:id])
  end

  # GET /marques/new
  def new
    @marque = Marque.new
  end

  # GET /marques/1/edit
  def edit
  end

  # POST /marques
  # POST /marques.json
  def create
    @marque = Marque.new(marque_params)

    respond_to do |format|
      if @marque.save
        format.html { redirect_to @marque, notice: 'Marque was successfully created.' }
        format.json { render :show, status: :created, location: @marque }
      else
        format.html { render :new }
        format.json { render json: @marque.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marques/1
  # PATCH/PUT /marques/1.json
  def update
    respond_to do |format|
      if @marque.update(marque_params)
        format.html { redirect_to @marque, notice: 'Marque was successfully updated.' }
        format.json { render :show, status: :ok, location: @marque }
      else
        format.html { render :edit }
        format.json { render json: @marque.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marques/1
  # DELETE /marques/1.json
  def destroy
    @marque.destroy
    respond_to do |format|
      format.html { redirect_to marques_url, notice: 'Marque was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marque
      @marque = Marque.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marque_params
      params.require(:marque).permit(:libelle)
    end
end

project/app/helpers/marques_helper.rb
module MarquesHelper
end

project/app/views/marques/_form.html.erb
<%= form_with(model: marque, local: true) do |form| %>
  <% if marque.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marque.errors.count, "error") %> prohibited this marque from being saved:</h2>

      <ul>
        <% marque.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :libelle %>
    <%= form.text_field :libelle %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/marques/edit.html.erb
<h1>Editing Marque</h1>

<%= render 'form', marque: @marque %>

<%= link_to 'Show', @marque %> |
<%= link_to 'Back', marques_path %>

project/app/views/marques/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marques</h1>

<table>
  <thead>
    <tr>
      <th>Libelle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marques.each do |marque| %>
      <tr>
        <td><%= marque.libelle %></td>
        <td><%= link_to 'Show', marque %></td>
        <td><%= link_to 'Edit', edit_marque_path(marque) %></td>
        <td><%= link_to 'Destroy', marque, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marque', new_marque_path %>

project/app/views/marques/new.html.erb
<h1>New Marque</h1>

<%= render 'form', marque: @marque %>

<%= link_to 'Back', marques_path %>

project/app/views/marques/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Libelle:</strong>
  <%= @marque.libelle %>
</p>

<p>
  <strong>Voituress</strong>
  <ul>
  <% @marque.voitures.each do |voiture| %>
    <li><%=link_to  voiture.modele, voiture_path(voiture.id) %></li>
   <% end %> 
    </ul>
</p>

<%= link_to 'Edit', edit_marque_path(@marque) %> |
<%= link_to 'Back', marques_path %>