project/config/routes.rb
Rails.application.routes.draw do
  resources :remove_marque_form_voitures
  resources :marques
  resources :personnes
  resources :voitures
  get 'voitures/immatriculation/:imat', to: 'voitures#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project/app/models/remove_marque_form_voiture.rb
class RemoveMarqueFormVoiture < ApplicationRecord
end

project/app/controllers/remove_marque_form_voitures_controller.rb
class RemoveMarqueFormVoituresController < ApplicationController
  before_action :set_remove_marque_form_voiture, only: [:show, :edit, :update, :destroy]

  # GET /remove_marque_form_voitures
  # GET /remove_marque_form_voitures.json
  def index
    @remove_marque_form_voitures = RemoveMarqueFormVoiture.all
  end

  # GET /remove_marque_form_voitures/1
  # GET /remove_marque_form_voitures/1.json
  def show
  end

  # GET /remove_marque_form_voitures/new
  def new
    @remove_marque_form_voiture = RemoveMarqueFormVoiture.new
  end

  # GET /remove_marque_form_voitures/1/edit
  def edit
  end

  # POST /remove_marque_form_voitures
  # POST /remove_marque_form_voitures.json
  def create
    @remove_marque_form_voiture = RemoveMarqueFormVoiture.new(remove_marque_form_voiture_params)

    respond_to do |format|
      if @remove_marque_form_voiture.save
        format.html { redirect_to @remove_marque_form_voiture, notice: 'Remove marque form voiture was successfully created.' }
        format.json { render :show, status: :created, location: @remove_marque_form_voiture }
      else
        format.html { render :new }
        format.json { render json: @remove_marque_form_voiture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /remove_marque_form_voitures/1
  # PATCH/PUT /remove_marque_form_voitures/1.json
  def update
    respond_to do |format|
      if @remove_marque_form_voiture.update(remove_marque_form_voiture_params)
        format.html { redirect_to @remove_marque_form_voiture, notice: 'Remove marque form voiture was successfully updated.' }
        format.json { render :show, status: :ok, location: @remove_marque_form_voiture }
      else
        format.html { render :edit }
        format.json { render json: @remove_marque_form_voiture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /remove_marque_form_voitures/1
  # DELETE /remove_marque_form_voitures/1.json
  def destroy
    @remove_marque_form_voiture.destroy
    respond_to do |format|
      format.html { redirect_to remove_marque_form_voitures_url, notice: 'Remove marque form voiture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_remove_marque_form_voiture
      @remove_marque_form_voiture = RemoveMarqueFormVoiture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def remove_marque_form_voiture_params
      params.require(:remove_marque_form_voiture).permit(:marque)
    end
end

project/app/helpers/remove_marque_form_voitures_helper.rb
module RemoveMarqueFormVoituresHelper
end

project/app/views/remove_marque_form_voitures/_form.html.erb
<%= form_with(model: remove_marque_form_voiture, local: true) do |form| %>
  <% if remove_marque_form_voiture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(remove_marque_form_voiture.errors.count, "error") %> prohibited this remove_marque_form_voiture from being saved:</h2>

      <ul>
        <% remove_marque_form_voiture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :marque %>
    <%= form.text_field :marque %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/remove_marque_form_voitures/edit.html.erb
<h1>Editing Remove Marque Form Voiture</h1>

<%= render 'form', remove_marque_form_voiture: @remove_marque_form_voiture %>

<%= link_to 'Show', @remove_marque_form_voiture %> |
<%= link_to 'Back', remove_marque_form_voitures_path %>

project/app/views/remove_marque_form_voitures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Remove Marque Form Voitures</h1>

<table>
  <thead>
    <tr>
      <th>Marque</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @remove_marque_form_voitures.each do |remove_marque_form_voiture| %>
      <tr>
        <td><%= remove_marque_form_voiture.marque %></td>
        <td><%= link_to 'Show', remove_marque_form_voiture %></td>
        <td><%= link_to 'Edit', edit_remove_marque_form_voiture_path(remove_marque_form_voiture) %></td>
        <td><%= link_to 'Destroy', remove_marque_form_voiture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Remove Marque Form Voiture', new_remove_marque_form_voiture_path %>

project/app/views/remove_marque_form_voitures/new.html.erb
<h1>New Remove Marque Form Voiture</h1>

<%= render 'form', remove_marque_form_voiture: @remove_marque_form_voiture %>

<%= link_to 'Back', remove_marque_form_voitures_path %>

project/app/views/remove_marque_form_voitures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marque:</strong>
  <%= @remove_marque_form_voiture.marque %>
</p>

<%= link_to 'Edit', edit_remove_marque_form_voiture_path(@remove_marque_form_voiture) %> |
<%= link_to 'Back', remove_marque_form_voitures_path %>