project/config/routes.rb
Rails.application.routes.draw do
  resources :remove_marque_form_voitures
  resources :marques
  resources :personnes
  resources :voitures
  get 'voitures/immatriculation/:imat', to: 'voitures#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project/app/models/voiture.rb
class Voiture < ApplicationRecord
    belongs_to :marque, required: false # Nom de la classe étrangère, en snake_case
    belongs_to :personne, required: false
    def age
        ((Date.today - date_mise_en_service)/365.25).floor
    end
    
end

project/app/controllers/voitures_controller.rb
class VoituresController < ApplicationController
  before_action :set_voiture, only: [:show, :edit, :update, :destroy]

  # GET /voitures
  # GET /voitures.json
  def index
    @voitures = Voiture.all
  end

  # GET /voitures/1
  # GET /voitures/1.json
  def show
  end

  # GET /voitures/new
  def new
    @voiture = Voiture.new
  end

  # GET /voitures/1/edit
  def edit
  end

  # POST /voitures
  # POST /voitures.json
  def create
    @voiture = Voiture.new(voiture_params)

    respond_to do |format|
      if @voiture.save
        format.html { redirect_to @voiture, notice: 'Voiture was successfully created.' }
        format.json { render :show, status: :created, location: @voiture }
      else
        format.html { render :new }
        format.json { render json: @voiture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /voitures/1
  # PATCH/PUT /voitures/1.json
  def update
    respond_to do |format|
      if @voiture.update(voiture_params)
        format.html { redirect_to @voiture, notice: 'Voiture was successfully updated.' }
        format.json { render :show, status: :ok, location: @voiture }
      else
        format.html { render :edit }
        format.json { render json: @voiture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /voitures/1
  # DELETE /voitures/1.json
  def destroy
    @voiture.destroy
    respond_to do |format|
      format.html { redirect_to voitures_url, notice: 'Voiture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def imat
    p params
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_voiture
      @voiture = Voiture.find(params[:imat])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def voiture_params
      params.require(:voiture).permit(:immatriculation, :couleur, :marque, :modele, :date_mise_en_service, :marque_id, :personne_id)
    end
end

project/app/helpers/voitures_helper.rb
module VoituresHelper
end

project/app/views/voitures/_form.html.erb
<%= form_with(model: voiture, local: true) do |form| %>
  <% if voiture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(voiture.errors.count, "error") %> prohibited this voiture from being saved:</h2>

      <ul>
        <% voiture.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :immatriculation %>
    <%= form.text_field :immatriculation %>
  </div>

  <div class="field">
    <%= form.label :couleur %>
    <%= form.text_field :couleur %>
  </div>

  <div class="field">
    <%= form.label :modele %>
    <%= form.text_field :modele %>
  </div>

  <div class="field">
    <%= form.label :date_mise_en_service %>
    <%= form.date_select :date_mise_en_service %>
  </div>
  <div class="field">
  <%= form.label :marque %>
    <%= form.collection_select :marque_id, Marque.order("libelle").all, :id, :libelle %>
  </div>

  <div class="field">
    <%= form.label :personne %>
    <%= form.collection_select :personne_id, Personne.order("noms").all, :id, :noms %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
  
  

<% end %>

project/app/views/voitures/_partialvoiture.html.erb
<p>
  <strong>Immatriculation:</strong>
  <%= voiture.immatriculation %>
</p>

<p>
  <strong>Couleur:</strong>
  <%= voiture.couleur %>
</p>

<p>
  <strong>Marque:</strong>
  <%= link_to voiture.try(:marque).try(:libelle), marque_path(voiture.marque_id) if voiture.marque %>
</p>

<p>
  <strong>Modele:</strong>
  <%= voiture.modele %>
</p>

<p>
  <strong>Date mise en service:</strong>
  <%= voiture.date_mise_en_service %>
</p>

project/app/views/voitures/edit.html.erb
<h1>Editing Voiture</h1>

<%= render 'form', voiture: @voiture %>

<%= link_to 'Show', @voiture %> |
<%= link_to 'Back', voitures_path %>

project/app/views/voitures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Voitures</h1>

<table>
  <thead>
    <tr>
      <th>Immatriculation</th>
      <th>Couleur</th>
      <th>Marque</th>
      <th>Modele</th>
      <th>Date mise en service</th>
      <th>propriétaire</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voitures.each do |voiture| %>
      <tr>
        <td><%= voiture.immatriculation %></td>
        <td><%= voiture.couleur %></td>
        <td><%= link_to voiture.marque.try(:libelle), marque_path(voiture.marque_id) if voiture.marque %></td>
        <td><%= voiture.modele %></td>
        <td><%= voiture.date_mise_en_service %></td>
        <td><%= link_to voiture.personne.try(:noms), personne_path(voiture.personne_id) if voiture.personne%></td>
        <td><%= link_to 'Show', voiture %></td>
        <td><%= link_to 'Edit', edit_voiture_path(voiture) %></td>
        <td><%= link_to 'Destroy', voiture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voiture', new_voiture_path %>

project/app/views/voitures/new.html.erb
<h1>New Voiture</h1>

<%= render 'form', voiture: @voiture %>

<%= link_to 'Back', voitures_path %>

project/app/views/voitures/show.html.erb
<p id="notice"><%= notice %></p>

<%= render partial: "partialvoiture", locals: {voiture: @voiture} %>

<p>
  <strong>Personne:</strong>
  <%= link_to @voiture.personne.try(:noms), personne_path(@voiture.personne_id) if @voiture.personne%>
</p>

<%= link_to 'Edit', edit_voiture_path(@voiture) %> |
<%= link_to 'Back', voitures_path %>