project/config/routes.rb
Rails.application.routes.draw do
  resources :remove_marque_form_voitures
  resources :marques
  resources :personnes
  resources :voitures
  get 'voitures/immatriculation/:imat', to: 'voitures#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

project/app/models/personne.rb
class Personne < ApplicationRecord
    has_many :voitures
end

project/app/controllers/personnes_controller.rb
class PersonnesController < ApplicationController
  before_action :set_personne, only: [:show, :edit, :update, :destroy]

  # GET /personnes
  # GET /personnes.json
  def index
    @personnes = Personne.all
  end

  # GET /personnes/1
  # GET /personnes/1.json
  def show
  end

  # GET /personnes/new
  def new
    @personne = Personne.new
  end

  # GET /personnes/1/edit
  def edit
  end

  # POST /personnes
  # POST /personnes.json
  def create
    @personne = Personne.new(personne_params)

    respond_to do |format|
      if @personne.save
        format.html { redirect_to @personne, notice: 'Personne was successfully created.' }
        format.json { render :show, status: :created, location: @personne }
      else
        format.html { render :new }
        format.json { render json: @personne.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personnes/1
  # PATCH/PUT /personnes/1.json
  def update
    respond_to do |format|
      if @personne.update(personne_params)
        format.html { redirect_to @personne, notice: 'Personne was successfully updated.' }
        format.json { render :show, status: :ok, location: @personne }
      else
        format.html { render :edit }
        format.json { render json: @personne.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personnes/1
  # DELETE /personnes/1.json
  def destroy
    @personne.destroy
    respond_to do |format|
      format.html { redirect_to personnes_url, notice: 'Personne was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personne
      @personne = Personne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personne_params
      params.require(:personne).permit(:noms, :prenom, :date_naissance)
    end
end

project/app/helpers/personnes_helper.rb
module PersonnesHelper
end

project/app/views/personnes/_form.html.erb
<%= form_with(model: personne, local: true) do |form| %>
  <% if personne.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(personne.errors.count, "error") %> prohibited this personne from being saved:</h2>

      <ul>
        <% personne.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :noms %>
    <%= form.text_field :noms %>
  </div>

  <div class="field">
    <%= form.label :prenom %>
    <%= form.text_field :prenom %>
  </div>

  <div class="field">
    <%= form.label :date_naissance %>
    <%= form.date_select :date_naissance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

project/app/views/personnes/edit.html.erb
<h1>Editing Personne</h1>

<%= render 'form', personne: @personne %>

<%= link_to 'Show', @personne %> |
<%= link_to 'Back', personnes_path %>

project/app/views/personnes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personnes</h1>

<table>
  <thead>
    <tr>
      <th>Noms</th>
      <th>Prenom</th>
      <th>Date naissance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personnes.each do |personne| %>
      <tr>
        <td><%= personne.noms %></td>
        <td><%= personne.prenom %></td>
        <td><%= personne.date_naissance %></td>
        <td><%= link_to 'Show', personne %></td>
        <td><%= link_to 'Edit', edit_personne_path(personne) %></td>
        <td><%= link_to 'Destroy', personne, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personne', new_personne_path %>

project/app/views/personnes/new.html.erb
<h1>New Personne</h1>

<%= render 'form', personne: @personne %>

<%= link_to 'Back', personnes_path %>

project/app/views/personnes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Noms:</strong>
  <%= @personne.noms %>
</p>

<p>
  <strong>Prenom:</strong>
  <%= @personne.prenom %>
</p>

<p>
  <strong>Date naissance:</strong>
  <%= @personne.date_naissance %>
</p>
<p>
  <strong>Voitures:</strong>
  <ul>
  <% @personne.voitures.each do |voiture| %>
    <li><%= render partial: "voitures/partialvoiture", locals: {voiture: voiture} %></li>
    <% end %> 
  </ul>
</p>


<%= link_to 'Edit', edit_personne_path(@personne) %> |
<%= link_to 'Back', personnes_path %>